spring:
  kafka:
    topics:
      completed: ${COMPLETED_TOPIC:transakcje-zrealizowane}
      expired: ${EXPIRED_TOPIC:transakcje-przeterminowane}
    bootstrap-servers: ${BOOTSTRAP_SERVERS:kafka1:9092,kafka2:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:~/test}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
springdoc:
  swagger-ui:
    url: /openapi.yaml
resources:
  cache:
    cachecontrol:
      no-store: true
    period: 0